"""Update students and markers tables

Revision ID: fe6c41902281
Revises: 
Create Date: 2025-07-09 23:36:30.980519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6c41902281'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('markers', sa.Column('longitude', sa.Float(), nullable=False))
    op.alter_column('markers', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('markers', 'lon')
    op.drop_column('markers', 'lat')
    op.alter_column('students', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('markers', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('markers', sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('markers', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('markers', 'longitude')
    op.drop_column('markers', 'latitude')
    # ### end Alembic commands ###
